### ISSUE TITLE
purdy-cli?

### ISSUE THREAD

**Issue by bfred-it** [danielb2/purdy.js#22]
Do you plan on including a cli interface to it?
It would be great to just do `curl a.com/file.json | purdy` or just `purdy file.json`

**Comment by danielb2** [comment]
Can do :)  I think I've done it once for myself already

**Comment by danielb2** [comment]
Sorry for the delay there ;) I'm traveling

**Comment by danielb2** [comment]
oh, and it can't do stdin yet. I'll work on that later. figured I'd at least make some progress to begin with

**Comment by bfred-it** [comment]
:+1:

**Comment by danielb2** [comment]
OK, now it does stdin, but you need to use 
`curl https://raw.githubusercontent.com/danielb2/purdy.js/master/package.json | purdy -`

Note the `-`
