### ISSUE TITLE
Nothing is printed if object has only Symbol properties

### ISSUE THREAD

**Issue by FredyC** [danielb2/purdy.js#26]
Kinda obvious culprit in the code there ... https://github.com/danielb2/purdy.js/blob/master/lib/index.js#L109.

    if (Object.keys(object).length === 0) {
        return '{}';
    }

Symbols are checked bit later.

**Comment by danielb2** [comment]
Can you give me an example of code that fails to print?  Just to be sure I have it to test against?

**Comment by FredyC** [comment]
Sure...

    const mySymbol = Symbol();
    const obj = {[mySymbol]: true};
    purdy(obj); // {} is printed

**Comment by danielb2** [comment]
@FredyC  thanks much

**Comment by FredyC** [comment]
I thank to you too. :+1:

**Comment by arb** [comment]
I feel like this should have been an option rather than the default behavior. If someone uses `Symbol` they are probably trying to hid some things from the public space... Just my two cents.

**Comment by FredyC** [comment]
Well I see `purdy` more like tool for debugging and seeing what's in the box, so it makes sense to see everything. The usual `console.log` wont show these which makes `purdy` superior over it.
