### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by FredyC** [danielb2/purdy.js#54]
I tried to stringify some error response object from superagent module. There is some list of event handlers and apparently it does not have a constructor which causes crash on this line: https://github.com/danielb2/purdy.js/blob/master/lib/index.js#L131

Apparently the purdy shouldn't rely so blindly that there will be a constructor. Sadly I am not sure how to reproduce that outside of scope of my project.

**Comment by danielb2** [comment]
released https://github.com/danielb2/purdy.js/tree/v2.2.1

**Comment by FredyC** [comment]
That was quick, thanks! :)
