### ISSUE TITLE
Purdy uses vulnerable version of hoek

### ISSUE THREAD

**Issue by hulmgulm-at-work** [danielb2/purdy.js#58]
Hi,

The version 2.16.3 of hoek, used by purdy, has a security vulnerability.
https://nodesecurity.io/advisories/566

Can you please update this dependency to a not vulnerable version?

Thank you!

**Comment by danielb2** [comment]
purdy doesn't use any of the affected functions ( merge, applyToDefaults, applyToDefaultsWithShallow )

**Comment by danielb2** [comment]
I'll accept a PR though
